project:
  type: website
  resources:
    - figs/
  render:
    - "*.qmd"

pagetitle: "surveydown Quant UX Con"
title: "`surveydown`<br><span style='font-size: 0.7em;'>An Open-Source, Markdown-Based Platform<br>for Reproducible and Programmable Surveys</span>"
author: "<br>**Pingfan Hu**<br>George Washington University<br><br>Quant UX Con 2025"

format:
  touhou-revealjs:
    smaller: false
    css: styles/slides.css
    include-after-body:
      - styles/bubble-align.html
    slide-number: true
    embed-resources: false
    auto-stretch: false
    footer: "<a href='http://pingfanhu.com'>Pingfan Hu</a> - <a href='https://www.quantuxa.org/quant-ux-con/quant-ux-con-2025'>Quant UX Con 2025</a>"
    preview-links: auto
    link-external-newwindow: true
    link-external-icon: false
    center-title-slide: true
    code-block-height: 650px
    title-slide-attributes:
      class: custom-title-slide
      style: "text-align:left; background-image: url(figs/logo-surveydown.png);"
      
execute:
  warning: false
  echo: false
